#!/bin/sh

# Render missile range generated by MISSILE-RANGE function from the
# CL-PROJ utils set in azimuthal-orthagonal projection

# MISSILE-RANGE generates a GeoJSON file, convert it to KML and then
# convert from KML to the GMT file format.

# English-language Wikipedia article estimates Hwasong-12 (KN-17)
# missile range to be within 3700-6000 km
# [https://en.wikipedia.org/w/index.php?oldid=794994024]. Therefore
# two circles will be drawn: the minimum and the maximum

RANGE_MIN_JSON=range-3700.json
RANGE_MAX_JSON=range-6000.json
RANGE_MIN_GMT=range-min.gmt
RANGE_MAX_GMT=range-max.gmt

ogr2ogr -f GMT $RANGE_MIN_GMT $RANGE_MIN_JSON
ogr2ogr -f GMT $RANGE_MAX_GMT $RANGE_MAX_JSON

INIT="-K"
APPEND="-K -O"
FINISH="-O"

ORIENT= #-P

plot() {
    PROJ=$1
    REGION=$2
    OUT=map_range_$3

    gmt pscoast -R${REGION} -J${PROJ} -Bag -Dc -A5000 -Gwhite -SDarkTurquoise $ORIENT $INIT > ${OUT}.ps

    # Plot country borders using the DCW dataset, in ASia, OCeania, North
    # America. It is also possible to plot borders using -N parameter, but
    # DCW appears to be more accurate and detailed
    gmt pscoast -R${REGION} -J${PROJ} -Bag -E=EU,=AS,=OC,=NA -Dc -A5000 -Gwhite -W0.25p,100/100/100 $ORIENT $APPEND >> ${OUT}.ps

    # Range circles
    gmt psxy $RANGE_MIN_GMT -R${REGION} -J${PROJ} -Baf -W0.75p,220/30/40 -Gred -t80 $ORIENT $APPEND >> ${OUT}.ps
    # Leave inner circle intact (not filled with any color) by clipping it
    gmt psclip $RANGE_MIN_GMT -R${REGION} -J${PROJ} -N $ORIENT $APPEND >> ${OUT}.ps
    gmt psxy $RANGE_MAX_GMT -R${REGION} -J${PROJ} -Baf -W0.75p,220/30/40 -Gred -t70 $ORIENT $APPEND >> ${OUT}.ps
    # Cancel clipping
    gmt psclip -C -R -J -Baf $ORIENT $APPEND >> ${OUT}.ps

    gmt pstext locations.txt -R${REGION} -J${PROJ} -F+f+a+j $ORIENT $APPEND >> ${OUT}.ps
    gmt psxy   locations.txt -R${REGION} -J${PROJ} -Sc0.12c -G204/0/0 -W0.5p $ORIENT $APPEND >> ${OUT}.ps
    gmt pstext select_capitals.txt -R${REGION} -J${PROJ} -F+f+a+j $ORIENT $APPEND >> ${OUT}.ps
    gmt psxy   select_capitals.txt -R${REGION} -J${PROJ} -Ss0.18c -G204/0/0 -W0.5p $ORIENT $FINISH >> ${OUT}.ps

    # transparency only works in the PDF format
    ps2pdf ${OUT}.ps ${OUT}.pdf
    
    # now it is possible to convert PDF to a much more simplier PNG
    convert -trim ${OUT}.pdf ${OUT}.png
}

# Direct the globe at the desired location:

#  -JGlon_0/lat_0/width

# where (lon_0, lat_0) is the center of the map (projection). Here, we
# center at Pyongyang

LAT=39
LON=126

# region g is for Globe
plot G${LON}/${LAT}/6i g azim-orth

# Mercator projection
plot m0.07c 0/360/-70/70 merc
